### ISSUE TITLE
Make website responsive for mobile devices

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/weave#1]
Hello Erol,

We need you to make http://staging.weavefamily.org responsive for mobile devices.

We did some work on this in the past in a branch called 'responsive' in Github, but have not got around to finishing it. I cannot guarantee that the work done there was the best approach, but you're welcome to use it if it is helpful. We have made some changes on the 'master' branch since then so you'll need to merge them if you decide to use the code from the 'responsive' branch.

Can you take a few hours to look at this and then provide an estimate of how much this task will cost?

I can provide you with:

1. Wordpress login to staging site
2. FTP access to staging site
3. DB dump

Let me know if you need anything else or have suggestions about a better workflow.

Thank you,
Malachi

**Comment by cmmadmin** [comment]
You will find a dump of the database in the root folder of the staging site.

FTP Username: weave-staging@everyethne.org
FTP server: ftp.everyethne.org
FTP & explicit FTPS port:  21

Wordpress login for staging site is:
Username: erolsk8@gmail.com

I will send the passwords for FTP and Wordpress accounts via email.

**Comment by erolsk8** [comment]
Great! Thank you.

I'll try to estimate this as close as possible with my friend, and I'll let you know.

**Comment by cmmadmin** [comment]
Would it be helpful if I added your friend as a collaborator on the Github project?

**Comment by cmmadmin** [comment]
If you can, please confirm the credentials I sent are working and you have everything you need. In a couple of hours I will be leaving and will be out of the office until next week.

**Comment by erolsk8** [comment]
WP login works, FTP access works, I found and dowloaded DB dump (uscwmmob_weave.sql).

And yes, I wanted to check if you could add him to this project. His username is: tahireu

Thank you

**Comment by cmmadmin** [comment]
Great! I have sent and invitation to tahireu to collaborate.

**Comment by erolsk8** [comment]
This template and installation is huge, so we didn't find better way to estimate, but to list all pages and try to predict average time it will take to do each page.


Pages we found:

1. Home http://staging.weavefamily.org/
2. Activities http://staging.weavefamily.org/thread/kazakhs/
3. Journal http://staging.weavefamily.org/journal/
4. Journal Detail http://staging.weavefamily.org/prayer-uprising-children-in-his-story-part-5/
5. Author http://staging.weavefamily.org/author/karen-hardin/
6. Author Articles http://staging.weavefamily.org/author/carissa-potter/?articles
7. Resource http://staging.weavefamily.org/resources/
8. Resource Detail http://staging.weavefamily.org/resource/living-your-legacy/
9. Big Story Training http://staging.weavefamily.org/big-story-training/
10. About http://staging.weavefamily.org/about-us/
11. Give http://staging.weavefamily.org/give/
12. Weave Families http://staging.weavefamily.org/weave-families/
13. Contact Us http://staging.weavefamily.org/contact-us/
14. Our Team http://staging.weavefamily.org/our-team/
15. Guest Authors http://staging.weavefamily.org/guest-authors/
16. Recipes http://staging.weavefamily.org/recipes/
17. Recipes Detail http://staging.weavefamily.org/recipe/buckwheat-pancakes/
18. Search Results http://staging.weavefamily.org/?s=lassi
19. Login / Register / Recover Password http://staging.weavefamily.org/login/
20. Profile http://staging.weavefamily.org/your-profile/


Erol: 10 (pages) * 5 (avg. h/page) * 25 (usd/h) = 1250 usd
Damir: 10 (pages) * 5 (avg. h/page) * 12.5 (usd/h) = 625 usd
Total: 1875 usd


Included in estimate:
- Estimate
- Project Setup
- Unexpected Stuff

Not included in estimate:
- New pages we didn't find so far

**Comment by cmmadmin** [comment]
Erol, 

I'd like to start by having you make the homepage responsive.  Then let's evaluate before we move ahead with the rest. Will that work?

What is your preferred method for responsive layouts? Do you use flexbox?

**Comment by erolsk8** [comment]
Would you like me to estimate how many hours it might take to do the homepage or should I run timers and we'll see how long it takes?  I'm asking because it's really hard to estimate something like this, so I'd prefer to run timers and to be paid hourly, instead of fixed amount. But I can try to come up with some fixed amount if you want.

And no, flexbox is not something that would be useful for this, that's something else. This is about changing CSS rules on certain screen widths using Media Queries (https://www.w3schools.com/css/css3_mediaqueries.asp). Some HTML might have to be adjusted as well. Rearranging elements in code (preserving current look) so elements can stack on top of each other on smaller screens. Like this: https://internetingishard.com/html-and-css/responsive-design.

**Comment by cmmadmin** [comment]
Erol, 

It seems like you are suggesting we go with adaptive design instead of responsive. I would prefer to go with responsive. Is there a reason you prefer adaptive? Or did I misunderstand?

https://css-tricks.com/the-difference-between-responsive-and-adaptive-design/

**Comment by tahireu** [comment]
Hello,

Sorry for interrupting your conversation. I hope my comment will make things more clear.

We are using combination of elements with relative width and different elements positioning on different screen sizes, which is considered as responsive layout: https://youtu.be/IgojC1D3QpU

Example - responsive layout we did for lifeline.org:
https://i.imgur.com/YObz8y8.gif

**Comment by erolsk8** [comment]
Exactly, we do not make only fluid or only adaptive, we do responsive design (https://youtu.be/T6MCkGWSXa0?t=43s).

**Comment by cmmadmin** [comment]
Thank you for the clarification. Go ahead and make the homepage responsive. You can keep track of your time with timers and we will pay you hourly.

**Comment by erolsk8** [comment]
Great, we just estimated that it might take between 15h and 20h to do homepage, because it includes header, footer, setting up everything, etc.

Please let me know if that is fine with you.

Also, we are thinking about using [Time Doctor](https://www.timedoctor.com/) (or something similar), which would not only keep track of time, but also take screenshots, track which websites and apps we used while we were working, and many more things. So that you can see exactly what we were doing.

**Comment by cmmadmin** [comment]
Ok. That sounds good. And using Time Doctor sounds good too.

**Comment by erolsk8** [comment]
I disabled these plugins: Google Analytics, Google Captcha, Redirection, WP-SpamShield and Yoast SEO. And now it's loading much faster.

**Comment by cmmadmin** [comment]
It looks great so far. Let's proceed with the following pages. This should include everything except the items in the More menu. Once this is done we'll evaluate how we're doing on budget before proceeding with the rest.

1. Activities http://staging.weavefamily.org/thread/kazakhs/
2. Journal http://staging.weavefamily.org/journal/
3. Journal Detail http://staging.weavefamily.org/prayer-uprising-children-in-his-story-part-5/
4. Author http://staging.weavefamily.org/author/karen-hardin/
5. Author Articles http://staging.weavefamily.org/author/carissa-potter/?articles
6. Resource http://staging.weavefamily.org/resources/
7. Resource Detail http://staging.weavefamily.org/resource/living-your-legacy/
8. Big Story Training http://staging.weavefamily.org/big-story-training/
9. Search Results http://staging.weavefamily.org/?s=lassi
10. Login / Register / Recover Password http://staging.weavefamily.org/login/
11. Profile http://staging.weavefamily.org/your-profile/

**Comment by erolsk8** [comment]
Sounds good. Do you maybe think it would be good if Damir did more work than me or maybe even most of the work? I would still double check everything to make sure it's all good. 

Because I'm slowly getting something else to work on, and it will be much better for the budget. I mean, I can work on this as well, it's not a problem for me at all, but I just wanted to check.

**Comment by cmmadmin** [comment]
Yes, that would be great to have do most of the work with your review. This
task is more budget sensitive.

**Comment by cmmadmin** [comment]
Erol,

How did you minify the responsive-header.js file?
I have deployed your changes to http://staging.weavefamily.org but cannot get the mobile dropdown menu to work. I am having trouble using the javascript debugger in Chrome because the file is minified.

Can you give me some tips?
-Malachi

**Comment by erolsk8** [comment]
I didn't, maybe some plugin is doing that. But I pushed a commit that should solve that.

**Comment by cmmadmin** [comment]
Hello Erol,



Let’s switch to a free option for time tracking. I appreciate all the work
you guys are doing. I will be busy with a server upgrade today. Let me know
if you have any additional questions and I’ll try to get back to you
tomorrow.



-Malachi



---------------------------------

*Malachi Wurpts* | Technology Director
Center for Mission Mobilization
PHONE | 479-587-9598 x112

*Building global momentum to help complete the Great Commission.*

*mobilization.org <http://mobilization.org/>* |  weavefamily.org |
*perspectives.org
<http://perspectives.org/>*

campusministry.org | *supportraisingsolutions.org
<http://supportraisingsolutions.org/>* | *cmmpress.org
<http://cmmpress.org/>*



*From:* erolsk8 <notifications@github.com>
*Sent:* Wednesday, July 4, 2018 12:17 PM
*To:* cmmadmin/weave <weave@noreply.github.com>
*Cc:* cmmadmin <admin@mobilization.org>; Mention <mention@noreply.github.com
>
*Subject:* Re: [cmmadmin/weave] Make website responsive for mobile devices
(#1)



Hi Malachi ( @cmmadmin <https://github.com/cmmadmin> ),

I just want to check if you were able to see how much we worked on Time
Doctor <https://www.timedoctor.com/>?

We registered for free trail (15 days), which will expire tomorrow, so I'm
not sure if we'll be able to access it, to get reports, screenshots and
things like that.

Please let me know if we should use some basic timers that are free, and
that can't take screenshots and all those additional features of Time
Doctor (app/website usage, idle time, etc.). Maybe something like Toggl. Or
if we should pay for Time Doctor to continue to use that.

Thanks

Erol

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cmmadmin/weave/issues/1#issuecomment-402529629>, or mute
the thread

**Comment by erolsk8** [comment]
Hi Malachi,

We finished those 11 pages. Please let me know if we missed something or if something needs to be changed. 

Thank you

Erol

**Comment by cmmadmin** [comment]
Hello Erol,

From what I've reviewed the pages look good so far. I'm no longer able to see the reports in Time Doctor. Can you provide me with the total number of hours each of you has worked so far?

-Malachi

**Comment by erolsk8** [comment]
Hi Malachi,

Damir worked **36.5h**, and I worked **13.5h**.

Here are reports I exported from TimeDoctor from 22/06 to 05/07: 
[from_2018_06_22_to_2018_07_05.zip](https://github.com/cmmadmin/weave/files/2174852/from_2018_06_22_to_2018_07_05.zip)

But Damir also worked on 06/07, so here is his report:
[damir_timesheet_report_from_2018_06_21_to_2018_07_07.csv.zip](https://github.com/cmmadmin/weave/files/2174863/damir_timesheet_report_from_2018_06_21_to_2018_07_07.csv.zip)

And this from Damir as well: https://we.tl/zMa0X1SV2R

Please let me know if this is sufficient.

Also, could we now sort out payments for what we did so far? It's getting a bit complicated do keep track of hours and all that. Especially if we'll be doing more pages and switch to Toggl.

Thanks

Erol

**Comment by cmmadmin** [comment]
Hello Erol,

Yes, we can make a payment for your work thus far. Can you send me an invoice by email including the total amount and the details we will need to perform the wire transfer?

Thanks to both of you for your great work on this project!

-Malachi

**Comment by erolsk8** [comment]
You're welcome! I'm glad you like it, and we can of course finish rest of the pages if you want.

I just want to check if we should send two separate invoices for bank transfers to **two accounts or just one account** and we'll then split it between us? We are ok with both ways, so please just let me know what's better for you.

**Comment by cmmadmin** [comment]
You can send two separate invoices for bank transfers to two accounts. We are OK with paying you both separately.

**Comment by cmmadmin** [comment]
I got approval to proceed. Please proceed to make the remaining pages in the More menu responsive which should include:

1. About http://staging.weavefamily.org/about-us/
2. Give http://staging.weavefamily.org/give/
3. Contact Us http://staging.weavefamily.org/contact-us/
4. Our Team http://staging.weavefamily.org/our-team/
5. Guest Authors http://staging.weavefamily.org/guest-authors/
6. Weave Families http://staging.weavefamily.org/weave-families/
7. Recipes http://staging.weavefamily.org/recipes/
8. Recipes Detail http://staging.weavefamily.org/recipe/buckwheat-pancakes/

It appears to be working well to have Damir to the primary work with Erol's review.
Thank you!

**Comment by erolsk8** [comment]
Great! That's how we'll continue, because I'm quite busy with other work, but I can still review and help Damir of course.

Damir is configuring supportraisingsolutions.org locally and then he will start with it. But since this is also approved - what should be priority?

Thanks

**Comment by cmmadmin** [comment]
Both are equal priority. Damir can choose to do them in whatever order is most efficient for him.

**Comment by tahireu** [comment]
I just wrote a comment (in https://github.com/cmmadmin/srs/issues/19) that I am able to start working on SRS tomorrow, but in this case I will finish these Weave pages first.

**Comment by tahireu** [comment]
Hello Malachi,

Responsive style for the pages from the More menu is finished and available in responsive-new branch. I will get in touch with Erol later today about preparing time reports and invoices for you.

I have a question about "Learn more about..." element. Although usually I didn't changed the way pages look on regular screens, fastest way to make this element responsive was to slightly change the location/position where the content is displayed after "Learn more about..." link is clicked. 
You can see the difference between: https://weavefamily.org/threads/ and http://staging.weavefamily.org/threads/ . Please let me know if this is acceptable. If not, I would need few more hours to find a way to make it responsive without changing the original page look.

Thanks, 
Damir

**Comment by cmmadmin** [comment]
The change to Learn More is acceptable as-is. 

Based on our initial review, your work looks good. Thank you.
Please send the final cost information in an invoice and we'll get you paid for this task.
