### ISSUE TITLE
New Page: The Big Story Series

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/weave#2]
Erol and Damir,

We have a new page that we would like you to develop for us. Are you available? Damir doing the primary work with Erol's review seems to be working well for us.

**This page is designed to accomplish the following:**
- Advertise The Big Story Series giving users reasons to believe and care about the series as a whole, as individual books, and individual resources
- Give users the option to download each individual resource at no cost
- Provide those who live in the U.S. the option to purchase individual books or all the books together as a bundle

**Navigation:**
- "Buy Now" will lead users to the CMM Press site.
- "Download for Free" will guide users through our required fields for download.

**Fonts:**
- Standard Weave website fonts +
- Alegreya Sans
- Palomino Sans

**Development direction | Header Ad**
Starry BG would be set as a background-image, while the Series Ad and thumbnail images would be an img floating on top. So on mobile, the world and book image would resize to the full size of the canvas, while the background image would resize as needed to keep the height and width it needs to cover the div.

**Development direction | Fonts**
It looks like the Weave site uses rem with 10px as the base. I propose changing the base for this page to 17px. So this h3, which is 1.4rem and is usually 14px, would be 23.8px. The h2 would be 3rem = 51px.

**Timing:**
The series will be available for purchase on Sept. 24th
Demand is high for downloads. It would be ideal to launch the page as soon as possible with "Comming Soon" under the "Buy Now" buttons if we can beat Sept. 24th by a substantial date. Otherwise, we'd like to shoot for Sept. 24th.

**Design File is attached**

[Big Story Series CL3.pdf](https://github.com/cmmadmin/weave/files/2329896/Big.Story.Series.CL3.pdf)

**Comment by cmmadmin** [comment]
You will find the following in the root of the Staging site:

- 2018-08-13-BigStorySeries.zip - all design files including Photoshop and source image files
- uscwmmob_weave.sql - db snapshot of live site

**Comment by erolsk8** [comment]
It sounds good to me. Damir can probably start with this when he finishes making those additional two pages responsive, but we'll see what he has to say.

**Comment by tahireu** [comment]
I am available for this task. I was planning to finish those additional two pages responsiveness until end of this week, so I can start working on this next week. Or, I can do this first, if this has higher priority.

**Comment by cmmadmin** [comment]
Damir, You can finish the two SRS pages and then start on this next week. That sounds like a good plan.

**Comment by tahireu** [comment]
I have a couple of questions:
- Is this a static page, or some content should come dynamically from WP backend?
- "Buy Now" will be simple hardcoded link to CMM Press site, or something more complex is needed to be implemented for this? 
- Similar question about "Download for Free" button: are those "required fields" on another page, site, or they should be displayed on this page?
- If I understood correctly, on smaller screens Starry BG should be 100% of the screen width, while world and book images should be enlarged in size relatively to Starry BG? If it is easier, you can provide me an illustration/image of how this should look on mobile devices.
- I would need PalominoSans One and PalominoSans Two fonts.

Thank you for your answers in advance. I downloaded the files, so they can be deleted from the drive.

**Comment by tahireu** [comment]
I would also suggest 2em for h2, because 34px is the actual size of h2 in Photoshop file (I am assuming that h2 should be used for One Big Story/Vision/Adventure sections big title). 
![screen shot 2018-09-04 at 4 50 43 pm](https://user-images.githubusercontent.com/25506516/45038945-ac5f2400-b062-11e8-916b-25bff5fff5ee.png)

**Comment by cmmadmin** [comment]
You are correct about the font sizes. We looked at the file and you are correct. h3 should be 1.4em = 23.8px and h2 should be 2em = 34px.

**Comment by cmmadmin** [comment]
> If I understood correctly, on smaller screens Starry BG should be 100% of the screen width, while world and book images should be enlarged in size relatively to Starry BG? If it is easier, you can provide me an illustration/image of how this should look on mobile devices.

Starry BG should be background-size: contain
Does that give enough direction?

**Comment by cmmadmin** [comment]
This page closely resembles this page:
https://weavefamily.org/big-story-training/

I suggest you start with a copy of that page template (page-bigstory.php).

**Comment by cmmadmin** [comment]
> I would need PalominoSans One and PalominoSans Two fonts.

We have setup a Web Font Project on fonts.com with Family Grouping enabled. You can add this to weave_scripts() in functions.php:

```
if( is_page('BigStorySeries') ) {	
  wp_enqueue_style('bigstoryfonts', 'https://fast.fonts.net/cssapi/8782d339-746f-49c0-8051-9e34c5cfce7d.css');
}
```

then you can use this in your css:

`font-family:'Palomino W00';`

**Comment by cmmadmin** [comment]
> "Buy Now" will be simple hardcoded link to CMM Press site, or something more complex is needed to be implemented for this?

Yes, all "Buy Now" links will be simple hardcoded link to CMM Press site.

> Similar question about "Download for Free" button: are those "required fields" on another page, site, or they should be displayed on this page?

These will be simple links to PDF files for now. We may change this to require a subscription form soon but we are still working on this.

> Is this a static page, or some content should come dynamically from WP backend?

Let's use the post title and content as follows:

The Big Story Series - <?php the_title(); ?>

Text section: "Open your children's hearts...everyone involved in the work" - <?php the_content(); ?>

The rest of the page can be hardcoded in the page template.

**Comment by cmmadmin** [comment]
That should address all your questions. Let me know if you need anything else.

**Comment by tahireu** [comment]
This is finished and available in responsive-new branch. 

- New page should use "Big Story Series" template
- This HTML code should be used as page body: 
```
<h3>
    Open your children’s hearts to peoples around the world who have never heard of Jesus. Discover God’s purposes and help your family find their role in God’s Big Story.
</h3>
<h3>
    Perfect for family devotions, these books are available for free as PDF downloads. You can also purchase physical books separately or as a bundle within the United States.
</h3>
<div>
    Interested in printing in your country or translating these into your language? Contact us to get the conversation started! We want to make these resources available to all in a way that honors everyone involved in the work.
</div>
```
- Featured image for the page should be Starry BG.jpg
- You will maybe need to install "Regenerate Thumbnail" plugin, go to Media, find new-added Starry BG.jpg image, open it, and click "Regenerate Thumbnail". If you want to avoid this, you can just use this Starry-BG-940x630.jpg attached here: [Starry-BG-940x630.jpg.zip](https://github.com/cmmadmin/weave/files/2375227/Starry-BG-940x630.jpg.zip)

- I followed your instructions:
> ...but it should be 100% of either the screen width or div height, whichever is lesser. Which is what background-size: contain does.

But this way, on smaller screens, hero content is too small (see first screenshot below). Erol suggested more prettier solution without that "background-size: contain" behavior for Starry BG.jpg (see second screenshot below). If you want me to do it this way, let me know.

Currently:
![screen shot 2018-09-12 at 3 11 42 pm](https://user-images.githubusercontent.com/25506516/45427025-1cdaf600-b69e-11e8-964e-30f4ea6b7d48.png)


Erol' suggestion: 
![screen shot 2018-09-12 at 3 13 34 pm](https://user-images.githubusercontent.com/25506516/45427072-43992c80-b69e-11e8-934b-87b73b7d4171.png)

**Comment by erolsk8** [comment]
If featured image is added through Media Library, there is no need for "Regenerate Thumbnail".

**Comment by cmmadmin** [comment]
> But this way, on smaller screens, hero content is too small (see first screenshot below). Erol suggested more prettier solution without that "background-size: contain" behavior for Starry BG.jpg (see second screenshot below). If you want me to do it this way, let me know.

Erol's suggestion for the hero content (see second screenshot below) looks good. Go ahead and implement it that way and let us know when it is ready. Thank you for offering these good solutions!

**Comment by tahireu** [comment]
Updated version is now available in responsive-new branch.

**Comment by cmmadmin** [comment]
Hello Damir, I'm sorry I thought I responded to this. The updates look good. Thank you for thinking of innovative ways to do this well. You can send us an invoice for this task.

It has all been deployed to the productions site.

**Comment by tahireu** [comment]
Ok, just keep in mind that url's for buttons are still not defined.
